name: License

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check_dependency_license:
    name: Check Dependency License
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v5
      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Check licenses
        run: pnpm dlx @cybozu/license-manager analyze -c license_manager/license-manager-prod.config.js

  check_devdependency_license:
      name: Check DevDependency License
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v6
        - name: Install pnpm
          uses: pnpm/action-setup@v5
        - name: Install node
          uses: actions/setup-node@v6
          with:
            node-version-file: "package.json"
            cache: 'pnpm'
        - name: Install Dependencies
          run: pnpm install --frozen-lockfile
        - name: Check licenses
          run: pnpm dlx @cybozu/license-manager analyze -c license_manager/license-manager-dev.config.js