name: execute garoon-plugin-uploader

on:
  pull_request:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v5
      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: 'pnpm'
      - name: Install Dependencies
        run: |
          pnpm install --frozen-lockfile
      - name: Install Chrome for Puppeteer
        run: |
          pnpm exec puppeteer browsers install chrome
      - name: run test
        run: |
          pnpm run lint
          pnpm run build
          node ./bin/cli.js --base-url ${{ secrets.GAROON_DOMAIN }} --username ${{ secrets.GAROON_USERNAME }} --password ${{ secrets.GAROON_PASSWORD }} --plugin-path ./utils/plugin.zip
          node ./bin/cli.js --base-url ${{ secrets.GAROON_DOMAIN }} --username ${{ secrets.GAROON_USERNAME }} --password ${{ secrets.GAROON_PASSWORD }} --plugin-path ./utils/plugin.zip --plugin-id ${{ secrets.GAROON_PLUGIN_ID }}
